spring:
  application:
    name: edge
server:
  port: 8070

---

spring:
  profiles: docker
  cloud:
    config:
      uri: http://config:8888
  boot:
    admin:
      url: http://admin:8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
